### ISSUE TITLE
스토리 보드 작성

### ISSUE THREAD

**Issue by dlehd333** [dlehd333/DKClinic#2]
스토리 보드 작성
- 사용 프로그램 : Oven(https://ovenapp.io/)

**Comment by D-Gun** [comment]
DKClinic 스토리보드 링크

https://ovenapp.io/view/kP4z1u39d7R7GKtusrBZgKVAnsvm6hEC#QYSwQ

**Comment by kaiascezar** [comment]
수정된 DKClinic 스토리보드 링크 : 
https://ovenapp.io/view/kP4z1u39d7R7GKtusrBZgKVAnsvm6hEC/LZN8F

변경점 : 전체 프로그램을 고객용, 직원용으로 분할한것을 반영, 2개의 프로젝트로 나누었음. 이에 따른 순서 조정 및 이름 변경

주의점 : 앱 가동을 위해 임시로 메인(선택창)을 남겨두었음. 실제 프로젝트에는 사용되지 않을 예정
