### ISSUE TITLE
DB 복구 완료시 해야할 일

### ISSUE THREAD

**Issue by D-Gun** [dlehd333/DKClinic#21]
#3 
Custom 테이블에는 Password 열이 필요없음, Employee에 필요한 부분이므로 확인후 수정.

**Comment by kaiascezar** [comment]
#3 
Customer 테이블 Password 열 삭제
Employee 테이블 Password 추가 - default : 본인 이름 이니셜
Customer, Employee 테이블 Birthdate 형식 nvarchar(50)으로 변경 - 생년월일 6자
