### ISSUE TITLE
CustomerProgram User Control 기능구현 - CustomerLoginControl

### ISSUE THREAD

**Issue by dlehd333** [dlehd333/DKClinic#22]
ctmLogin 기능 구현

- 확인 이벤트 2개 생성(신규회원용, 기존회원용)
- 신규회원 : Customer클래스에 값 삽입, ctmInputDetail생성
- 기존회원 : CustomerID, ctmInputDetail생성

- 확인 버튼 누를 시 메세지박스 출력

- 메세지박스 닫히면 이벤트 실행

**Comment by dlehd333** [comment]
이벤트 2개 -> 1개로 변경
인자값 : 값이 삽입된 Customer클래스, 생성한 ctmInputDetail UC (생성자로 Customer클래스를 보낸다)

**Comment by dlehd333** [comment]
테스트용으로 쓸만한 Customer 테이블 데이터
Name : Test / Birthdate : 900101
Name : 한글테스트 / Birthdate : 800101

**Comment by kaiascezar** [comment]
ctmLogin 기능 구현

확인 이벤트 1개 생성 - Clear
신규회원 // 기존회원 - 틀만 잡음. CustomerDao Find 정의해야 함.
확인 버튼 누를 시 메세지박스 출력 // 메세지박스 닫히면 이벤트 실행 - 구현만 됨. 아직 실행 X

막힌 부분
일반적인 using var 사용하려고 했음 -> "" 인용 실수로 막힘.(" -> \")
Dao 활용을 제대로 하지 못함 -> 김프로님께 배움

추가할 부분
이름변경
ctmInputDetail과의 연동 정리(변수명 등)
취소버튼 동작(user control은 자체 close 기능이 없음 -> main에서 해결해야함)

**Comment by kaiascezar** [comment]
확인버튼 이벤트 : LoginToDetail(Customer customer, CustomerInputDetailControl ctmInputDetail)
취소버튼 : 텍스트박스 클리어
