### ISSUE TITLE
CustomerProgram User Control 기능구현 - CustomerDepartmentChoiceControl

### ISSUE THREAD

**Issue by dlehd333** [dlehd333/DKClinic#25]
- 이벤트 1개 추가
- 인자값 : DepartmentID, 생성한 ctmQuestionnare UC (생성자로 DepartmentID)

**Comment by kaiascezar** [comment]
이벤트(DepartmentToQuestionnare)

인자 Department department, CustomerQuestionnareControl custQuestionnare(haha)

**Comment by kaiascezar** [comment]
#41 구현 완

DB연동 후 확인하면 주석 제거 예정

직원프로그램 작업 후 버튼 통합 예정
