### ISSUE TITLE
Database Schema 설계

### ISSUE THREAD

**Issue by dlehd333** [dlehd333/DKClinic#3]
- 사용 Database : Microsoft SQL Server 2019
- 사용 IDE : Microsoft SQL Server Management Studio 18
- 사용 서버 : 클래스 내에서 제공한 로컬 서버

**Comment by kaiascezar** [comment]
Not Confirmed yet :(
![DB Schema(Not Confirmed)](https://user-images.githubusercontent.com/74527101/99943229-4f232a80-2db4-11eb-8759-e68acdca4d77.JPG)

**Comment by D-Gun** [comment]
Class Table 이름 Position 으로 변경 (코딩 진행시 충돌 우려) (Not rank)
Speciality Table 이름 Department로 변경
Questionnaire Table 에 DoctorID(int) 열 추가, Employee Table과 1:다 관계 형성
Department Table에 Count(int)열 추가 - 문제 삭제 및 추가시 변경되는 문항 수 저장을 목적으로 함

**Comment by kaiascezar** [comment]
Confirmed :)

![DB Schema1(Confirmed)](https://user-images.githubusercontent.com/74527101/99954516-40de0a00-2dc6-11eb-8c85-bbbb51cc4a33.JPG)
![DB Schema2(Confirmed)](https://user-images.githubusercontent.com/74527101/99954520-420f3700-2dc6-11eb-9276-5d5439ffd609.JPG)

**Comment by dlehd333** [comment]
![스키마아](https://user-images.githubusercontent.com/69996028/100204184-e5875580-2f46-11eb-8f67-5cca8d74486e.png)

**Comment by D-Gun** [comment]
Gender 테이블 Name->Gender로 변경

**Comment by kaiascezar** [comment]
Customer, Employee, Question 테이블 데이터 입력
Position 관리자 -> 병원장
Gender, Department 테이블 변동사항 없음
Questionnaire, Diagnosis 테이블은 프로그램 내에서 작성하면 생성될 예정
