### ISSUE TITLE
프로젝트 생성 및 EF 연결

### ISSUE THREAD

**Issue by dlehd333** [dlehd333/DKClinic#4]

**Comment by D-Gun** [comment]
Form size 선정
size : 1280 X 720 (16:9)
subform size :  1024 X 768 (4:3)

**Comment by D-Gun** [comment]
form size 1280 X 720 -> 1280 X 820 로 변경 (툴바 추가)

**Comment by dlehd333** [comment]
mainform size : 1280 X 820
user control : 1280 X 720
subform size : 1024 X 768

**Comment by dlehd333** [comment]
프로젝트 구조 조정
- 이전 : 메인 -> 직원메뉴, 손님메뉴 구조(Winform 1개)
- 이후 : 직원용 프로그램, 손님용 프로그램 개별 구성(Winform 2개)

**Comment by dlehd333** [comment]
EF연결 작업 완료
https://github.com/dlehd333/DKClinic/commit/e5f5736d3c92dc4725943d541a7d30c5f3387a08

**Comment by dlehd333** [comment]
user control : 1280 X 720 -> 1262 X 673 으로 변경

**Comment by kaiascezar** [comment]
mainform size : 1280 X 820
user control : 1262 X 673
subform size : 1024 X 768

login form button set : location 400, 900 // size 180, 95 // font 24(좌하단 기준)
datagridview set : location 100, 10 // size 1062, 500(검색x) or 450(검색o) // anchor T L R
datagridview button set : location 100, 550 // size 180, 95 // font 24(좌하단 기준)

버튼의 세로크기는 고정, 가로사이즈는 텍스트내용, 버튼의 갯수에 따라 조정이 가능함.
