### ISSUE TITLE
EmployeeProgram User Control 기능 구현 - EmployeeSelectFunctionControl

### ISSUE THREAD

**Issue by dlehd333** [dlehd333/DKClinic#44]
※ CustomerProgram 프로젝트의 CustomerDepartmentChoiceControl과 구조가 비슷함

---
- Employee클래스를 매개변수로 받는 생성자 추가 생성
(Employee클래스는 선택 가능한 메뉴를 판별(PositionID)하기 위해 사용)
---
- 이벤트 1개 생성, 매개변수는 버튼에 따른 다음 페이지의 컨트롤(BaseUC타입) 1개.
- 버튼 클릭시 생성하는 다음 페이지의 컨트롤의 생성자 매개변수는 Employee클래스 1개.
- 이벤트의 매개변수로 Employee클래스는 들어가지 않음. 값이 변경되지 않기 때문에 전달 필요 없음.

**Comment by kaiascezar** [comment]
이벤트 - SelectToFunction(BaseUC baseUC)

각 버튼 클릭시 해당하는 작업의 유저컨트롤 띄우기
