### ISSUE TITLE
문진표 문제 수정 이슈

### ISSUE THREAD

**Issue by dlehd333** [dlehd333/DKClinic#5]
문진표 문제를 수정하는 기능을 구현할 때,
수정 이전에 작성한 문진표를 출력해야 하는 이슈가 있다.

**Comment by D-Gun** [comment]
문진표 항목(질문) 추가 후 기존 테이블 구성을 변경할 때, 고려해야 할 사항 두가지 발생
  질문에 index 추가하여 질문 정렬 시
  -  신규 작성된 질문보다 아래에 정렬 될 질문들에게는 새로 index를 부여 해야함.
  -  신규 작성된 질문이 우리가 원하는 위치에 정렬될 것이란 보장이 없음

**Comment by dlehd333** [comment]
문진표 문제를 수정하는 기능을 구현할 때 생길 수 있는 이슈
- 추가/수정/삭제 이전에 작성된 문진표를 출력할 떄, 이전에 작성된 문제가 출력되야 한다. 하지만 추가/수정/삭제가 진행된 문제 데이터를 가져오면 문제가 생길 수 있다
-> 데이터베이스에 저장되어 있는 문제를 직접 건들지 않고 변경된 문제를 추가하는 방식으로 이전 문제롤 보존한다
-> 작성된 문진표를 읽어들일때는 문진표 문제 테이블의 ID값을 이용해 불러온다
- 수정된 최신의 버전의 문진표 문제를 불러오기 위해(신규 문진표 작성), 문진표 문제 테이블에 작성된 문제가 수정된 문제인지 아닌지 구분할 방법이 필요하다
-> 문진표 문제 테이블에 "버전정보"컬럼을 추가하여, 해당 문제에 대해 최신 버전의 문제를 가져올 수 있도록 한다

**Comment by kaiascezar** [comment]
문진표 질문 수정 및 삭제 관련 이슈

- 환자가 문진표를 작성하기 위한 질문이 출력될때는, 항상 수정/추가/삭제 된 질문들이 출력되어야 한다.
- 의사가 환자의 문진표를 열람할 때, 만약 문진표가 수정/추가/삭제 되기 이전에 작성된 것이라면, 이전 상태의 항목이
  출력되어야 한다.
  -> 단순히 항목을 수정 하는것으로는 해결이 되지 않음

- 수정과 추가가 반영되는 방향이 다르기 때문에, 통일할 필요가 있다
   -> 모든 수정 및 추가는 '추가'하는 방향으로 통일. 기존의 항목을 구분할 추가 인자가 필요함
   -> version(latest version) 요소를 추가하여 구분자를 지음.
