### ISSUE TITLE
이름짓기

### ISSUE THREAD

**Issue by kaiascezar** [dlehd333/DKClinic#7]

**Comment by kaiascezar** [comment]
[변수명s.xlsx](https://github.com/dlehd333/DKClinic/files/5586945/s.xlsx)

시작 |   |   |   |   |   |   |   |   |   |   | 직원 |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | Mainform |   |   |   |   |   |   |   |   |   | 직원로그인 | empLogin |   |   |   |  
  |   |   | lblTitle |   |   |   |   |   |   |   |   |   |   | lbl1 |   |   |  
  |   | btnHome |   |   | btnExit |   |   |   |   |   |   |   | lbl2 |   | txbName |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   | lbl3 |   | txbPassword |  
  |   | lblStatus |   |   | lblNowTime |   |   |   |   |   |   |   | btnChangePw |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   | btnOK |   | btnCancel |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
환자 |   |   |   |   |   |   |   |   |   |   | pw변경 | empChangePw |   |   |   |  
환자로그인 | ctmLogin |   |   |   |   |   |   |   |   |   |   |   | lbl1 |   | txbName |   |  
  |   |   | label |   |   |   |   |   |   |   |   |   | lbl2 |   | txbOldPw |   |  
  |   | lbl1 |   | txbName |   |   |   |   |   |   |   |   | lbl3 |   | txbNewPw |  
  |   | lbl2 |   | txbBirthdate |   |   |   |   |   |   |   | lbl4 |   | txbNewPwCheck |  
  |   |   |   |   |   |   | ` |   |   |   |   |   | btnOK |   | btnCancel |   |  
  |   | btnOK |   | btnCancel |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   | 작업선택 | empSelectFunction |   |   |   |  
추가정보 | ctmInputDetail |   |   |   |   |   |   |   |   |   |   | btnManageQuestionare | btnManageQuestion
  |   | lbl1 |   | txbName |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   | lbl2 |   | txbBirthdate |   |   |   |   |   |   |   | btnManageCtm |   | btnManageEmp
  |   | lbl3 |   | rbtMale | lbl5 | rbtFemale | lbl6 |   |   |   |   |   |   |   |   |   |  
  |   | lbl4 |   | txbCellphone |   |   |   |   |   | 문진표관리 | empManageQuestionare |   |   |  
  |   | btnOK |   | btnCancel |   |   |   |   |   |   |   |   | dgvQuestionareList |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
진료과선택 | ctmDepChoice |   |   |   |   |   |   |   |   |   |   | btnOpenResponse | btnDelete |   | btnGoBack
  |   | btnMG |   | btnNU |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   | 열람/진단서 작성 | Response |   |   |   |   |  
  |   | btnDR |   | btnFM |   |   |   |   |   |   |   |   | lbl |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   | pnlBoard |   |   |   |  
문진표작성 | ctmQuestionare |   |   |   |   |   |   |   |   |   |   | lbl |   |   |   |  
  |   | pnlBoard | MultipleChoice | vsbQuestionare |   |   |   |   |   |   | txbDiagnosis |   |   |  
  |   |   | ShortAnswer |   |   |   |   |   |   |   |   |   |   | btnSave | btnCancel |  
  |   |   | MultipleChoices |   |   | btnSubmit |   |   |   |   |   |   |   |   |  
  |   |   |   | lblQuestion | lblQuestion | lblQuestion |   | 환자관리 | empManageCtm |   |   |   |  
  |   |   |   | rbtList |   | ckbList |   | txbAnswer |   |   |   | dgvCtmList |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   | lbl | txbName |   | btnSearch |  
  |   |   |   |   |   |   |   |   |   |   |   |   | btnUpdate | btnDelete |   | btnGoBack
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   | 환자정보 | empUpdateCtmInfo(폼) | ctmDetail을 불러옴 |  
  |   |   |   |   |   |   |   |   |   |   |   |   | lbl1 |   | txbName |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   | lbl2 |   | txbBirthdate |  
  |   |   |   |   |   |   |   |   |   |   |   |   | lbl3 |   | rbtMale | lbl5 | rbtFemale
  |   |   |   |   |   |   |   |   |   |   |   |   | lbl4 |   | txbCellphone |  
  |   |   |   |   |   |   |   |   |   |   |   |   | btnOK |   | btnCancel |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   | 직원관리 | empManageEmp |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   | dgvEmpList |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   | lbl | txbName |   | btnSearch |  
  |   |   |   |   |   |   |   |   |   |   |   |   | btnUpdate | btnDelete |   | btnGoBack
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   | 직원정보 | empUpdateEmpInfo(폼) |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   | lbl1 |   | txbName |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   | lbl2 |   | txbBirthdate |  
  |   |   |   |   |   |   |   |   |   |   |   |   | lbl3 |   | rbtMale | lbl5 | rbtFemale
  |   |   |   |   |   |   |   |   |   |   |   |   | lbl4 |   | txbCellphone |  
  |   |   |   |   |   |   |   |   |   |   |   |   | lbl5 |   | txbPosition |  
  |   |   |   |   |   |   |   |   |   |   |   |   | lbl6 |   | txbDepartment |  
  |   |   |   |   |   |   |   |   |   |   |   |   | btnOK |   | btnCancel |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   | 질문관리 | empManageQuestion |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   | dgvQuestionList |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   | btnAdd | btnUpdate | btnDelete | btnSave | btnGoBack
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   | 질문수정 | empModifyQuestion(폼) |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   | txbIndexNum | txbItem |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   | cmbSelectType | txbChoices |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | btnSave | btnCancel

**Comment by dlehd333** [comment]
ctmQuestionare 컨트롤 내부에 pnlBoard 컨트롤에 들어가는 3종류의 문제를 나타내는 컨트롤 MultipleChoice, ShortAnswer, MultipleChoices 3개 중 이름이 비슷해 혼동가능한 MultipleChoice, MultipleChioces를 MultipleChoice 하나로 줄이고, 기능(객관식, 객관식다중선택)을 하나로 합친다.

**Comment by kaiascezar** [comment]
이상하게 줄인것들 그냥 풀어쓰기 ex) ctm = customer // emp = employee
DB의 customer table과 C#의 customer  project 이름이 겹침   ->  C# CustomerPrograme으로 변경 예정

**Comment by dlehd333** [comment]
변경 규칙 : 
- 이름 중 emp나 ctm이 두번 들어간 경우 뒤에것을 지우고 작성함
-  Form은 접미어로 Form을 붙여주고, User Control은 접미어로 Control을 붙여줌

**Comment by D-Gun** [comment]
EmployeeCheckResponseDiagnosisForm 생성 후 변수 명 아래와 같이 변경


열람/진단서 작성 | EmployeeCheckResponseDiagnosisForm |  
-- | -- | --|--|
  |   | lblCustomerName |   |  
  |   | pnlBoard |   |   |  
  |   | label2 |   |   |  
  |   | txbDiagnosis |   |  
  |   |   |   | btnSave | btnCancel
